import Vue from "vue";
import { Button, Search, Swipe, SwipeItem, Toast, Icon, Tag, List, Cell, DropdownMenu, DropdownItem } from "vant";
Vue.use(Button);
Vue.use(Search);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Toast);
Vue.use(Icon);
Vue.use(Tag);
Vue.use(List);
Vue.use(Cell);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
